import Foundation
import ActivityAssistantCore

/// `swift run corecheck`            — run every check
/// `swift run corecheck --trials`   — replay the eight scripted trials and
///                                    print the table used in TEST_RESULTS.md
@main
struct CoreCheck {
    @MainActor
    static func main() async {
        if CommandLine.arguments.contains("--trials") {
            await TrialHarness.run()
            return
        }

        // Reads a `/predict` body on stdin and runs it through the real client
        // decoder. `scripts/smoke_test.py` pipes live responses from the
        // Python service through this, so the two halves of the contract are
        // checked against each other rather than against two copies of the
        // same assumption.
        if CommandLine.arguments.contains("--decode") {
            decodeStdin()
            return
        }

        print("ActivityAssistantCore — flow and wire-format checks")
        await FlowChecks.run()
        await WireFormatChecks.run()
        exit(Check.summarize())
    }
}

/// Emits one line of `key=value` on success, or `error=<detail>` on failure,
/// so the Python side can assert on it without parsing Swift types.
@MainActor
private func decodeStdin() {
    let input = FileHandle.standardInput.readDataToEndOfFile()
    do {
        let prediction = try Prediction.decode(from: input)
        let scores = prediction.scores
            .map { "\($0.activity.rawValue):\(String(format: "%.4f", $0.score))" }
            .joined(separator: ",")
        print("ok label=\(prediction.activity.rawValue) "
              + "confidence=\(String(format: "%.4f", prediction.confidence)) "
              + "margin=\(String(format: "%.4f", prediction.margin)) "
              + "modalities=\(prediction.modalities.map(\.rawValue).sorted().joined(separator: "+")) "
              + "scores=\(scores)")
    } catch let error as PredictionError {
        print("error \(error.diagnosticDescription)")
        exit(2)
    } catch {
        print("error \(error)")
        exit(2)
    }
}

// MARK: - Eight-trial replay

/// Replays eight scripted trials through the real state machine, so the table
/// in `docs/TEST_RESULTS.md` is generated by the same engine that runs on
/// device rather than transcribed by hand.
///
/// ## The numbers below are PLACEHOLDERS, not measurements
///
/// Nobody has run this on glasses. The labels, confidences, timings and notes
/// are chosen to exercise every branch the engine can take — a confident hit, a
/// low-confidence decline, a confident miss, and an endpoint failure — so the
/// table's format and arithmetic are right and the report has something
/// concrete to be written against.
///
/// Replace them with your own observations before submitting. See the warning
/// at the top of `docs/TEST_RESULTS.md`; presenting these as experimental
/// results would be fabrication.
@MainActor
enum TrialHarness {

    struct Trial {
        let groundTruth: Activity
        let response: ScriptedImageBindClient.Response
        let seconds: Double
        let note: String
    }

    static let trials: [Trial] = [
        .init(groundTruth: .walking,
              response: .prediction(.sample(.walking, confidence: 0.88, runnerUp: .running)),
              seconds: 1.9, note: "Hallway, even lighting"),
        .init(groundTruth: .walking,
              response: .prediction(.sample(.walking, confidence: 0.74, runnerUp: .standing)),
              seconds: 2.1, note: "Turning a corner, motion blur"),
        .init(groundTruth: .running,
              response: .prediction(.sample(.running, confidence: 0.91, runnerUp: .walking)),
              seconds: 1.8, note: "Treadmill, audio clearly helped"),
        .init(groundTruth: .running,
              response: .prediction(.sample(.running, confidence: 0.83, runnerUp: .walking)),
              seconds: 2.0, note: "Outdoors, wind on the mic"),
        .init(groundTruth: .sitting,
              response: .prediction(.sample(.sitting, confidence: 0.69, runnerUp: .standing)),
              seconds: 1.7, note: "Desk, subject facing camera"),
        .init(groundTruth: .sitting,
              response: .prediction(.sample(.sitting, confidence: 0.34, runnerUp: .standing)),
              seconds: 1.8, note: "LOW CONFIDENCE — waist-up crop, no chair visible"),
        .init(groundTruth: .standing,
              response: .prediction(.sample(.sitting, confidence: 0.52, runnerUp: .standing)),
              seconds: 1.9, note: "MISS — leaning on a desk, read as sitting"),
        .init(groundTruth: .standing,
              response: .failure(.timedOut(seconds: 12)),
              seconds: 12.0, note: "ENDPOINT FAILURE — Colab tunnel recycled"),
    ]

    /// A clock the engine reads twice per trial (start, finish). Feeding it a
    /// scripted pair per trial keeps the durations in the generated table
    /// deterministic across runs, so re-running the harness never silently
    /// changes a number the report quotes.
    private final class ScriptedClock: @unchecked Sendable {
        private let lock = NSLock()
        private var stamps: [Double]

        init(stamps: [Double]) { self.stamps = stamps }

        func read() -> Double {
            lock.lock()
            defer { lock.unlock() }
            return stamps.isEmpty ? 0 : stamps.removeFirst()
        }
    }

    static func run() async {
        var stamps: [Double] = []
        var now = 0.0
        for trial in trials {
            stamps.append(now)                    // start of the run
            now += trial.seconds
            stamps.append(now)                    // terminal frame on the HUD
            now += 3.0                            // wearer reads it, taps Try Again
        }
        let clock = ScriptedClock(stamps: stamps)

        let device = ScriptedWearableDevice(name: "Scripted device (simulated)")
        let client = ScriptedImageBindClient(responses: trials.map(\.response))
        let engine = ActivityAssistantEngine(
            device: device,
            client: client,
            configuration: ServiceConfiguration(
                endpoint: URL(string: "https://example.invalid")!,
                confidenceFloor: 0.45
            ),
            clock: { clock.read() }
        )

        for trial in trials {
            engine.pendingGroundTruth = trial.groundTruth
            await engine.analyzeOnce()
        }

        emitTable(engine.trials)
        emitSummary(engine.trials)
    }

    private static func emitTable(_ records: [TrialRecord]) {
        print("| # | Ground truth | Outcome | Top-1 | Conf. | Margin | Audio | Time | Notes |")
        print("|---|---|---|---|---|---|---|---|---|")
        for (record, trial) in zip(records, trials) {
            let outcome: String
            let top1: String
            let confidence: String
            let margin: String

            switch record.outcome {
            case .predicted(let prediction):
                outcome = record.isCorrect ? "✅ correct" : "❌ wrong"
                top1 = prediction.activity.displayName
                confidence = format(prediction.confidence)
                margin = format(prediction.margin)
            case .lowConfidence(let prediction):
                outcome = "⚠️ low-confidence"
                top1 = prediction.activity.displayName
                confidence = format(prediction.confidence)
                margin = format(prediction.margin)
            case .failed(let error):
                outcome = "🛑 \(error.glassesMessage)"
                top1 = "—"
                confidence = "—"
                margin = "—"
            }

            print("| \(record.index) | \(record.groundTruth?.displayName ?? "—") | \(outcome) "
                  + "| \(top1) | \(confidence) | \(margin) | \(record.usedAudio ? "yes" : "no") "
                  + "| \(String(format: "%.1f s", record.totalSeconds)) | \(trial.note) |")
        }
    }

    private static func emitSummary(_ records: [TrialRecord]) {
        let correct = records.filter(\.isCorrect).count
        let lowConfidence = records.filter {
            if case .lowConfidence = $0.outcome { return true } else { return false }
        }.count
        let failed = records.filter {
            if case .failed = $0.outcome { return true } else { return false }
        }.count
        let answered = records.count - lowConfidence - failed
        let completedSeconds = records
            .filter { if case .failed = $0.outcome { return false } else { return true } }
            .map(\.totalSeconds)

        print("")
        print("- Trials: **\(records.count)** across all four activities (2 each)")
        // Guard the division: a run where every trial declined or failed leaves
        // `answered` at zero, and 0/0 is NaN — which `percent` then feeds to
        // `Int(...)`, trapping and crashing the harness instead of printing a
        // table. That is a plausible run, not a hypothetical: point the app at
        // a dead endpoint for all eight trials and you get exactly it.
        let accuracy = answered > 0
            ? " — of these, **\(correct) correct** (\(percent(Double(correct) / Double(answered))))"
            : " — no trial produced a confident answer"
        print("- Confident answers: **\(answered)**\(accuracy)")
        print("- Declined (below the 0.45 floor): **\(lowConfidence)**")
        print("- Endpoint failures: **\(failed)**")
        if !completedSeconds.isEmpty {
            let mean = completedSeconds.reduce(0, +) / Double(completedSeconds.count)
            print("- Median end-to-end latency on completed trials: "
                  + "**\(String(format: "%.1f s", median(completedSeconds)))** "
                  + "(mean \(String(format: "%.1f s", mean)))")
        }
    }

    private static func format(_ value: Double) -> String {
        String(format: "%.2f", value)
    }

    private static func percent(_ value: Double) -> String {
        "\(Int((value * 100).rounded()))%"
    }

    private static func median(_ values: [Double]) -> Double {
        let sorted = values.sorted()
        let middle = sorted.count / 2
        return sorted.count.isMultiple(of: 2)
            ? (sorted[middle - 1] + sorted[middle]) / 2
            : sorted[middle]
    }
}
